name: Build & Release MundoDonghua Extension

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Clona el repo
      - uses: actions/checkout@v4

      # 2. Configura JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Da permisos a gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. Compila con Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # 5. Sube como artifact
      - name: Upload Extension Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MundoDonghua
          path: build/libs/*.cs3

      # 6. Crea/actualiza un Release "latest"
      - name: Create or Update Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*.cs3
          name: "MundoDonghua Extension"
          tag_name: latest
          prerelease: false
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 7. Genera la attestation
      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: build/libs/*.cs3
